name: dominosee
channels:
  - conda-forge
dependencies:
  - netcdf4
  - numba
  - numpy
  - pandas
  - python=3.11
  - xarray
  - ipykernel
  - cartopy
  - matplotlib
  - cf_xarray
  - bottleneck
  - dask
  - scipy
