name: Deploy Documentation

on:
  push:
    branches: [ main ]  # Change this to your default branch if different
  pull_request:
    branches: [ main ]  # Change this to your default branch if different
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev,docs]'  # Install package in development mode with dev and docs extras
          
      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          
      - name: Build documentation
        run: |
          cd docs
          make html
          
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build/html
          branch: gh-pages  # The branch the action should deploy to
          clean: true  # Automatically remove deleted files from the deploy branch
